apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: confighpas.confighpa.shareit.com
spec:
  group: confighpa.shareit.com
  names:
    kind: ConfigHpa
    plural: confighpas
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            downscaleForbiddenWindowSeconds:
              format: int32
              maximum: 600
              minimum: 1
              type: integer
            maxReplicas:
              format: int32
              maximum: 1000
              minimum: 1
              type: integer
            metrics:
              items:
                type: object
              type: array
            minReplicas:
              format: int32
              maximum: 1000
              minimum: 1
              type: integer
            scaleDownLimitFactor:
              format: double
              maximum: 100
              minimum: 1
              type: number
            scaleTargetRef:
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
              required:
              - kind
              - name
              type: object
            scaleUpLimitFactor:
              format: double
              maximum: 100
              minimum: 1
              type: number
            tolerance:
              format: double
              maximum: 0.99
              minimum: 0.01
              type: number
            upscaleForbiddenWindowSeconds:
              format: int32
              maximum: 600
              minimum: 1
              type: integer
          required:
          - scaleTargetRef
          - maxReplicas
          type: object
        status:
          properties:
            conditions:
              items:
                type: object
              type: array
            currentMetrics:
              items:
                type: object
              type: array
            currentReplicas:
              format: int32
              type: integer
            desiredReplicas:
              format: int32
              type: integer
            lastScaleTime:
              format: date-time
              type: string
            observedGeneration:
              format: int64
              type: integer
          required:
          - currentReplicas
          - desiredReplicas
          - currentMetrics
          - conditions
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
